In [1]:
import pandas as pd
import numpy as np
import yfinance as yf

In [2]:
squares = []
for i in range(1, 11):
    squares.append(i ** 2)
print(squares)


def mean(values):
    total = sum(values)
    count = len(values)
    return total / count


print(mean([2, 4, 6, 8]))  
print(mean(squares))

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
5.0
38.5

In [3]:
returns = [0.02] * 12
growth = 1.0
for r in returns:
    growth = growth * (1 + r)
print(growth)

1.2682417945625455

In [4]:
prices = pd.Series([100, 120, 108, 129.6])
returns = prices.pct_change()
print(returns)

0    NaN
1    0.2
2   -0.1
3    0.2
dtype: float64

In [5]:
returns1 =[]
for i in range(1, len(prices)):
    returns1.append(prices[i]/prices[i-1]-1)

print(returns1)

[np.float64(0.19999999999999996), np.float64(-0.09999999999999998), np.float64(0.19999999999999996)]

In [6]:
multipliers = returns + 1

total_return = multipliers.prod() - 1
print(total_return)  


log_returns = np.log(multipliers)
print(np.exp(log_returns.sum()) - 1)

0.29600000000000004
0.29600000000000004

In [7]:
thy = yf.download("THYAO.IS", start="2020-01-01", auto_adjust=True )["Close"]
thy.tail()

[*********************100%***********************]  1 of 1 completed

Ticker      THYAO.IS
Date
2026-10-13    286.25
2026-10-14    279.25
2026-10-15    276.75
2026-10-16    273.50
2026-10-19    267.50

In [8]:
print(thy.shape)
print("\n")
print(thy.columns)
print("\n")
print(thy.index)
print("\n")
print(type(thy))
print("\n")
print(thy.tail())
print("\n")
print(thy.head())
print("\n")
print(thy.isna().sum())
print("\n")
thy.info()
print(thy.describe())

(1701, 1)


Index(['THYAO.IS'], dtype='str', name='Ticker')


DatetimeIndex(['2020-01-02', '2020-01-03', '2020-01-06', '2020-01-07',
               '2020-01-08', '2020-01-09', '2020-01-10', '2020-01-13',
               '2020-01-14', '2020-01-15',
               ...
               '2026-10-06', '2026-10-07', '2026-10-08', '2026-10-09',
               '2026-10-12', '2026-10-13', '2026-10-14', '2026-10-15',
               '2026-10-16', '2026-10-19'],
              dtype='datetime64[s]', name='Date', length=1701, freq=None)


<class 'pandas.DataFrame'>


Ticker      THYAO.IS
Date
2026-10-13    286.25
2026-10-14    279.25
2026-10-15    276.75
2026-10-16    273.50
2026-10-19    267.50


Ticker       THYAO.IS
Date
2020-01-02  14.487192
2020-01-03  13.940138
2020-01-06  13.256318
2020-01-07  13.227012
2020-01-08  13.187937


Ticker
THYAO.IS    0
dtype: int64


<class 'pandas.DataFrame'>
DatetimeIndex: 1701 entries, 2020-01-02 to 2026-10-19
Data columns (total 1 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   THYAO.IS  1701 non-null   float64
dtypes: float64(1)
memory usage: 26.6 KB
Ticker     THYAO.IS
count   1701.000000
mean     160.781764
std      126.631593
min        7.561083
25%       14.311353
50%      146.630325
75%      288.500000
max      348.250000

In [9]:
thy_series = thy["THYAO.IS"]
print(type(thy_series))
print(thy_series.head())

<class 'pandas.Series'>
Date
2020-01-02    14.487192
2020-01-03    13.940138
2020-01-06    13.256318
2020-01-07    13.227012
2020-01-08    13.187937
Name: THYAO.IS, dtype: float64

In [10]:
daily_returns = thy_series.pct_change()

In [11]:
print(type(daily_returns))
print(len(daily_returns))
print(daily_returns.isna().sum())
print(daily_returns.max())
print(daily_returns.min())

<class 'pandas.Series'>
1701
1
0.2165216770643963
-0.1494483847129484

In [12]:
print(thy_series.idxmax())
print(thy_series.idxmin())

2026-07-07 00:00:00
2020-03-23 00:00:00

In [13]:

check = pd.DataFrame({
    "price": thy_series,
    "return_pct": (daily_returns * 100).round(2),
})


print(check.loc["2020-03-18":"2020-03-26"])

print(check.loc["2026-07-02":"2026-07-10"])

               price  return_pct
Date
2020-03-18  7.756460        0.25
2020-03-19  7.746691       -0.13
2020-03-20  7.795536        0.63
2020-03-23  7.561083       -3.01
2020-03-24  8.117908        7.36
2020-03-25  8.537967        5.17
2020-03-26  9.045948        5.95
             price  return_pct
Date
2026-07-02  333.25        1.45
2026-07-03  334.00        0.23
2026-07-06  347.00        3.89
2026-07-07  348.25        0.36
2026-07-08  332.00       -4.67
2026-07-09  338.25        1.88
2026-07-10  344.50        1.85

In [14]:
daily_returns.max()

np.float64(0.2165216770643963)

In [17]:
print(check.loc["2023-02-03":"2023-02-20"])

                 price  return_pct
Date
2023-02-03  139.401367        6.02
2023-02-06  136.666092       -1.96
2023-02-07  124.259659       -9.08
2023-02-08  112.341682       -9.59
2023-02-15  136.666092       21.65
2023-02-16  136.763794        0.07
2023-02-17  138.033737        0.93
2023-02-20  138.033737        0.00

In [18]:
daily_returns.idxmin()

Timestamp('2020-03-12 00:00:00')

In [28]:

check.loc["2020-03-06 00:00:00":"2020-03-18 00:00:00"  ]

                price  return_pct
Date
2020-03-06  10.872722       -4.95
2020-03-09  10.140058       -6.74
2020-03-10   9.739535       -3.95
2020-03-11   9.739535        0.00
2020-03-12   8.283978      -14.94
2020-03-13   8.889647        7.31
2020-03-16   8.039756       -9.56
2020-03-17   7.736923       -3.77
2020-03-18   7.756460        0.25

In [43]:
growth_factors = daily_returns + 1
total_return_a = growth_factors.prod() - 1


log_returns = np.log(growth_factors)
total_return_b = np.exp(log_returns.sum()) - 1


total_return_c = thy_series.iloc[-1] / thy_series.iloc[0] - 1

print(total_return_a)
print(total_return_b)
print(total_return_c)

17.464585625546636
17.464585625546633
17.464585625546626